base_url = "https://sabatierboris.github.io"
compile_sass = false

build_search_index = false

theme = "zola-clean-blog"
description = "Boris Sabatier"

taxonomies = [
    {name = "categories", rss = false, paginate_by=5},
    {name = "tags", rss = false, paginate_by=5},
]

[markdown]
highlight_code = false

[extra]
clean_blog_menu = [
]

clean_blog_social = [
]
