base_url = "https://sabatierboris.github.io"
generate_rss = false
compile_sass = false
build_search_index = false

theme = "zola-clean-blog"
description = "Boris Sabatier"

taxonomies = [
    {name = "categories", rss = false, paginate_by=5},
    {name = "tags", rss = false, paginate_by=5},
]

[markdown]
highlight_code = false

[extra]
author = "Boris"
clean_blog_menu = [
    {url = "$BASE_URL/", name = "Blog"},
    {url = "$BASE_URL/about", name = "À propos"},
]

clean_blog_social = [
]
